title: Blws Blog
description: > # this means to ignore newlines until "baseurl:"
<br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bluewings2017.github.io" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'Blue'
  last_name: 'Wings'
  cv: '//kaptn.ru'
  avatar: '/images/logo.svg'
  github_username:  BlueWings2017 
  email: blws.co.kr
  vk_id: id201664979
  telegram_name: BlueWings2017 
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html


